name: Second CI

on:
  # push
   workflow_dispatch
jobs:
    build:
         runs-on: ubuntu-latest

         steps:        

            -name: Say Hello
            run:  echo "Hello from second" 

            -name: Install
            env:
               APP_ENV: demo
            run: echo "Enviroment $APP_ENV"
               
