name: env try

on:
 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from second"

      - name: Install
        env:
          APP_ENV: demonew
          DB_PASS: ${{  secrets.DB_PASS  }}
        run: echo "Environment $APP_ENV using $DB_PASS"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test job
        run: echo "Test job"
